import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface CitationReportData {
  clientName: string
  agencyName: string
  reportPeriod: string
  totalCitations: number
  avgPosition: number
  topPlatform: string
  sentimentBreakdown: {
    positive: number
    neutral: number
    negative: number
  }
  topQueries: Array<{
    query: string
    citations: number
    avgPosition: number
  }>
  dashboardUrl: string
}

async function generateCitationReport(html: string, data: CitationReportData): Promise<string> {
  const {
    clientName,
    agencyName,
    reportPeriod,
    totalCitations,
    avgPosition,
    topPlatform,
    sentimentBreakdown,
    topQueries,
    dashboardUrl
  } = data

  const positivePercentage = totalCitations > 0
    ? Math.round((sentimentBreakdown.positive / totalCitations) * 100)
    : 0

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AI Citation Report - ${clientName}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
            background-color: #f6f9fc;
          }
          .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #10b981;
          }
          .logo {
            font-size: 28px;
            font-weight: bold;
            color: #0f1419;
            margin-bottom: 8px;
          }
          .logo span {
            color: #10b981;
          }
          .metric-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin: 30px 0;
          }
          .metric-card {
            background: #f8fafc;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            border: 1px solid #e2e8f0;
          }
          .metric-number {
            font-size: 32px;
            font-weight: bold;
            color: #10b981;
            margin-bottom: 8px;
          }
          .metric-label {
            color: #64748b;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .query-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 12px 0;
            border-bottom: 1px solid #e2e8f0;
          }
          .query-text {
            flex: 1;
            margin-right: 16px;
          }
          .query-stats {
            display: flex;
            gap: 16px;
            font-size: 14px;
            color: #64748b;
          }
          .cta-button {
            display: inline-block;
            background: #10b981;
            color: white;
            padding: 16px 32px;
            text-decoration: none;
            border-radius: 8px;
            font-weight: 600;
            margin: 30px 0;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            color: #64748b;
            font-size: 14px;
            text-align: center;
          }
          .positive { color: #10b981; }
          .neutral { color: #64748b; }
          .negative { color: #ef4444; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <div class="logo">
              kreativ<span>pique</span>
            </div>
            <h1>AI Citation Report for ${clientName}</h1>
            <p style="color: #64748b; margin: 0;">
              ${reportPeriod} • Generated by ${agencyName}
            </p>
          </div>

          <div style="margin-bottom: 30px;">
            <h2 style="color: #1f2937; margin-bottom: 20px;">📊 Performance Overview</h2>

            <div class="metric-grid">
              <div class="metric-card">
                <div class="metric-number">${totalCitations}</div>
                <div class="metric-label">Total Citations</div>
              </div>

              <div class="metric-card">
                <div class="metric-number">#${avgPosition}</div>
                <div class="metric-label">Avg Position</div>
              </div>

              <div class="metric-card">
                <div class="metric-number">${positivePercentage}%</div>
                <div class="metric-label">Positive Sentiment</div>
              </div>

              <div class="metric-card">
                <div class="metric-number">${topPlatform}</div>
                <div class="metric-label">Top Platform</div>
              </div>
            </div>
          </div>

          <div style="margin-bottom: 30px;">
            <h2 style="color: #1f2937; margin-bottom: 20px;">🎯 Top Performing Queries</h2>
            <div>
              ${topQueries.slice(0, 5).map(query => `
                <div class="query-item">
                  <div class="query-text">
                    <strong>${query.query}</strong>
                  </div>
                  <div class="query-stats">
                    <span>${query.citations} citations</span>
                    <span>#${query.avgPosition} avg</span>
                  </div>
                </div>
              `).join('')}
            </div>
          </div>

          <div style="margin-bottom: 30px;">
            <h2 style="color: #1f2937; margin-bottom: 20px;">😊 Sentiment Analysis</h2>
            <div style="display: flex; gap: 20px; justify-content: space-around;">
              <div style="text-align: center;">
                <div style="font-size: 24px; font-weight: bold;" class="positive">
                  ${sentimentBreakdown.positive}
                </div>
                <div style="font-size: 14px; color: #64748b;">Positive</div>
              </div>
              <div style="text-align: center;">
                <div style="font-size: 24px; font-weight: bold;" class="neutral">
                  ${sentimentBreakdown.neutral}
                </div>
                <div style="font-size: 14px; color: #64748b;">Neutral</div>
              </div>
              <div style="text-align: center;">
                <div style="font-size: 24px; font-weight: bold;" class="negative">
                  ${sentimentBreakdown.negative}
                </div>
                <div style="font-size: 14px; color: #64748b;">Negative</div>
              </div>
            </div>
          </div>

          <div style="text-align: center;">
            <a href="${dashboardUrl}" class="cta-button">
              View Full Dashboard
            </a>
          </div>

          <div class="footer">
            <p>
              This report was automatically generated by kreativpique.<br>
              © 2025 ${agencyName}. All rights reserved.
            </p>
            <p style="margin-top: 16px; font-size: 12px;">
              Want to unsubscribe? <a href="#" style="color: #10b981;">Manage preferences</a>
            </p>
          </div>
        </div>
      </body>
    </html>
  `
}

async function sendEmail(to: string[], subject: string, html: string) {
  const resendApiKey = Deno.env.get('RESEND_API_KEY')
  if (!resendApiKey) {
    throw new Error('Resend API key not configured')
  }

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${resendApiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'kreativpique <reports@kreativpique.com>',
      to: to,
      subject: subject,
      html: html,
    }),
  })

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`Failed to send email: ${error}`)
  }

  return await response.json()
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false
        }
      }
    )

    // Get the current date for the report period
    const now = new Date()
    const firstDayOfMonth = new Date(now.getFullYear(), now.getMonth(), 1)
    const lastDayOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0)

    const reportPeriod = `${firstDayOfMonth.toLocaleDateString('en-US', {
      month: 'long',
      year: 'numeric'
    })}`

    // Get all active agencies
    const { data: agencies, error: agenciesError } = await supabase
      .from('agencies')
      .select(`
        *,
        users!inner(
          id,
          email,
          full_name,
          role
        )
      `)
      .eq('users.role', 'owner')

    if (agenciesError) {
      throw new Error(`Failed to fetch agencies: ${agenciesError.message}`)
    }

    const reports = []

    // Generate reports for each agency
    for (const agency of agencies || []) {
      // Get agency clients
      const { data: clients } = await supabase
        .from('clients')
        .select('*')
        .eq('agency_id', agency.id)
        .eq('is_active', true)

      if (!clients || clients.length === 0) continue

      // For each client, generate a report
      for (const client of clients) {
        // Get citations for this month
        const { data: citations } = await supabase
          .from('citations')
          .select('*')
          .eq('client_id', client.id)
          .gte('detected_at', firstDayOfMonth.toISOString())
          .lte('detected_at', lastDayOfMonth.toISOString())

        if (!citations || citations.length === 0) continue

        // Calculate metrics
        const totalCitations = citations.length

        // Average position
        const positionsWithValues = citations.filter(c => c.position !== null)
        const avgPosition = positionsWithValues.length > 0
          ? positionsWithValues.reduce((sum, c) => sum + (c.position || 0), 0) / positionsWithValues.length
          : 0

        // Top platform
        const platformCounts = new Map<string, number>()
        citations.forEach(c => {
          platformCounts.set(c.platform, (platformCounts.get(c.platform) || 0) + 1)
        })
        const topPlatform = Array.from(platformCounts.entries())
          .sort(([,a], [,b]) => b - a)[0]?.[0] || ''

        // Sentiment breakdown
        const sentimentBreakdown = {
          positive: citations.filter(c => c.sentiment === 'positive').length,
          neutral: citations.filter(c => c.sentiment === 'neutral').length,
          negative: citations.filter(c => c.sentiment === 'negative').length
        }

        // Top queries
        const queryCounts = new Map<string, { count: number; positions: number[] }>()
        citations.forEach(c => {
          const existing = queryCounts.get(c.query) || { count: 0, positions: [] }
          existing.count++
          if (c.position !== null) existing.positions.push(c.position)
          queryCounts.set(c.query, existing)
        })

        const topQueries = Array.from(queryCounts.entries())
          .map(([query, { count, positions }]) => ({
            query,
            citations: count,
            avgPosition: positions.length > 0
              ? Number((positions.reduce((sum, p) => sum + p, 0) / positions.length).toFixed(1))
              : 0
          }))
          .sort((a, b) => b.citations - a.citations)
          .slice(0, 5)

        // Prepare report data
        const reportData: CitationReportData = {
          clientName: client.name,
          agencyName: agency.name,
          reportPeriod,
          totalCitations,
          avgPosition: Number(avgPosition.toFixed(1)),
          topPlatform,
          sentimentBreakdown,
          topQueries,
          dashboardUrl: `${Deno.env.get('APP_URL') || 'https://app.kreativpique.com'}/clients/${client.id}`
        }

        // Generate HTML
        const html = await generateCitationReport('', reportData)

        // Send to agency owner and client contact (if provided)
        const recipients = [agency.users.email]
        if (client.contact_email) {
          recipients.push(client.contact_email)
        }

        // Send email
        const emailResult = await sendEmail(
          recipients,
          `AI Citation Report: ${client.name} - ${reportPeriod}`,
          html
        )

        reports.push({
          client: client.name,
          agency: agency.name,
          recipients: recipients.length,
          emailId: emailResult.id
        })

        console.log(`✅ Report sent for ${client.name} (${agency.name})`)

        // Add delay to respect rate limits
        await new Promise(resolve => setTimeout(resolve, 1000))
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        message: `Sent ${reports.length} monthly reports`,
        reports
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    )

  } catch (error) {
    console.error('Error sending reports:', error)
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    )
  }
})