import React from 'react'

// Citation Report Email Template
export interface CitationReportData {
  clientName: string
  agencyName: string
  reportPeriod: string
  totalCitations: number
  avgPosition: number
  topPlatform: string
  sentimentBreakdown: {
    positive: number
    neutral: number
    negative: number
  }
  topQueries: Array<{
    query: string
    citations: number
    avgPosition: number
  }>
  dashboardUrl: string
}

export const CitationReportTemplate = ({ data }: { data: CitationReportData }) => {
  const {
    clientName,
    agencyName,
    reportPeriod,
    totalCitations,
    avgPosition,
    topPlatform,
    sentimentBreakdown,
    topQueries,
    dashboardUrl
  } = data

  const positivePercentage = totalCitations > 0
    ? Math.round((sentimentBreakdown.positive / totalCitations) * 100)
    : 0

  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>AI Citation Report - {clientName}</title>
        <style dangerouslySetInnerHTML={{
          __html: `
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              line-height: 1.6;
              color: #333;
              margin: 0;
              padding: 0;
              background-color: #f6f9fc;
            }
            .container {
              max-width: 600px;
              margin: 0 auto;
              background: white;
              padding: 40px;
              border-radius: 8px;
              box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            .header {
              text-align: center;
              margin-bottom: 30px;
              padding-bottom: 20px;
              border-bottom: 2px solid #10b981;
            }
            .logo {
              font-size: 28px;
              font-weight: bold;
              color: #0f1419;
              margin-bottom: 8px;
            }
            .logo span {
              color: #10b981;
            }
            .metric-grid {
              display: grid;
              grid-template-columns: repeat(2, 1fr);
              gap: 20px;
              margin: 30px 0;
            }
            .metric-card {
              background: #f8fafc;
              padding: 20px;
              border-radius: 8px;
              text-align: center;
              border: 1px solid #e2e8f0;
            }
            .metric-number {
              font-size: 32px;
              font-weight: bold;
              color: #10b981;
              margin-bottom: 8px;
            }
            .metric-label {
              color: #64748b;
              font-size: 14px;
              text-transform: uppercase;
              letter-spacing: 0.5px;
            }
            .query-item {
              display: flex;
              justify-content: space-between;
              align-items: center;
              padding: 12px 0;
              border-bottom: 1px solid #e2e8f0;
            }
            .query-text {
              flex: 1;
              margin-right: 16px;
            }
            .query-stats {
              display: flex;
              gap: 16px;
              font-size: 14px;
              color: #64748b;
            }
            .cta-button {
              display: inline-block;
              background: #10b981;
              color: white;
              padding: 16px 32px;
              text-decoration: none;
              border-radius: 8px;
              font-weight: 600;
              margin: 30px 0;
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e2e8f0;
              color: #64748b;
              font-size: 14px;
              text-align: center;
            }
            .positive { color: #10b981; }
            .neutral { color: #64748b; }
            .negative { color: #ef4444; }
          `
        }} />
      </head>
      <body>
        <div className="container">
          <div className="header">
            <div className="logo">
              kreativ<span>pique</span>
            </div>
            <h1>AI Citation Report for {clientName}</h1>
            <p style={{ color: '#64748b', margin: 0 }}>
              {reportPeriod} • Generated by {agencyName}
            </p>
          </div>

          <div style={{ marginBottom: '30px' }}>
            <h2 style={{ color: '#1f2937', marginBottom: '20px' }}>📊 Performance Overview</h2>

            <div className="metric-grid">
              <div className="metric-card">
                <div className="metric-number">{totalCitations}</div>
                <div className="metric-label">Total Citations</div>
              </div>

              <div className="metric-card">
                <div className="metric-number">#{avgPosition}</div>
                <div className="metric-label">Avg Position</div>
              </div>

              <div className="metric-card">
                <div className="metric-number">{positivePercentage}%</div>
                <div className="metric-label">Positive Sentiment</div>
              </div>

              <div className="metric-card">
                <div className="metric-number">{topPlatform}</div>
                <div className="metric-label">Top Platform</div>
              </div>
            </div>
          </div>

          <div style={{ marginBottom: '30px' }}>
            <h2 style={{ color: '#1f2937', marginBottom: '20px' }}>🎯 Top Performing Queries</h2>
            <div>
              {topQueries.slice(0, 5).map((query, index) => (
                <div key={index} className="query-item">
                  <div className="query-text">
                    <strong>{query.query}</strong>
                  </div>
                  <div className="query-stats">
                    <span>{query.citations} citations</span>
                    <span>#{query.avgPosition} avg</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ marginBottom: '30px' }}>
            <h2 style={{ color: '#1f2937', marginBottom: '20px' }}>😊 Sentiment Analysis</h2>
            <div style={{ display: 'flex', gap: '20px', justifyContent: 'space-around' }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '24px', fontWeight: 'bold' }} className="positive">
                  {sentimentBreakdown.positive}
                </div>
                <div style={{ fontSize: '14px', color: '#64748b' }}>Positive</div>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '24px', fontWeight: 'bold' }} className="neutral">
                  {sentimentBreakdown.neutral}
                </div>
                <div style={{ fontSize: '14px', color: '#64748b' }}>Neutral</div>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '24px', fontWeight: 'bold' }} className="negative">
                  {sentimentBreakdown.negative}
                </div>
                <div style={{ fontSize: '14px', color: '#64748b' }}>Negative</div>
              </div>
            </div>
          </div>

          <div style={{ textAlign: 'center' }}>
            <a href={dashboardUrl} className="cta-button">
              View Full Dashboard
            </a>
          </div>

          <div className="footer">
            <p>
              This report was automatically generated by kreativpique.<br />
              © 2025 {agencyName}. All rights reserved.
            </p>
            <p style={{ marginTop: '16px', fontSize: '12px' }}>
              Want to unsubscribe? <a href="#" style={{ color: '#10b981' }}>Manage preferences</a>
            </p>
          </div>
        </div>
      </body>
    </html>
  )
}

// Alert Email Template
export interface AlertData {
  clientName: string
  agencyName: string
  alertType: 'high_value_citation' | 'negative_sentiment' | 'new_platform'
  platform: string
  query: string
  position: number
  context: string
  sentimentScore: number
  dashboardUrl: string
}

export const AlertTemplate = ({ data }: { data: AlertData }) => {
  const {
    clientName,
    agencyName,
    alertType,
    platform,
    query,
    position,
    context,
    sentimentScore,
    dashboardUrl
  } = data

  const getAlertTitle = () => {
    switch (alertType) {
      case 'high_value_citation':
        return `🎉 High-Value Citation Alert`
      case 'negative_sentiment':
        return `⚠️ Negative Sentiment Alert`
      case 'new_platform':
        return `🆕 New Platform Citation`
      default:
        return `📢 Citation Alert`
    }
  }

  const getAlertColor = () => {
    switch (alertType) {
      case 'high_value_citation':
        return '#10b981'
      case 'negative_sentiment':
        return '#ef4444'
      case 'new_platform':
        return '#3b82f6'
      default:
        return '#64748b'
    }
  }

  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{getAlertTitle()} - {clientName}</title>
        <style dangerouslySetInnerHTML={{
          __html: `
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              line-height: 1.6;
              color: #333;
              margin: 0;
              padding: 0;
              background-color: #f6f9fc;
            }
            .container {
              max-width: 600px;
              margin: 0 auto;
              background: white;
              padding: 40px;
              border-radius: 8px;
              box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            .alert-header {
              text-align: center;
              margin-bottom: 30px;
              padding: 20px;
              background: ${getAlertColor()}10;
              border-radius: 8px;
              border-left: 4px solid ${getAlertColor()};
            }
            .alert-title {
              font-size: 24px;
              font-weight: bold;
              color: ${getAlertColor()};
              margin-bottom: 8px;
            }
            .context-box {
              background: #f8fafc;
              padding: 20px;
              border-radius: 8px;
              border-left: 4px solid #10b981;
              margin: 20px 0;
            }
            .detail-item {
              display: flex;
              justify-content: space-between;
              padding: 8px 0;
              border-bottom: 1px solid #e2e8f0;
            }
            .detail-label {
              font-weight: 600;
              color: #374151;
            }
            .detail-value {
              color: #64748b;
            }
            .cta-button {
              display: inline-block;
              background: #10b981;
              color: white;
              padding: 16px 32px;
              text-decoration: none;
              border-radius: 8px;
              font-weight: 600;
              margin: 30px 0;
            }
          `
        }} />
      </head>
      <body>
        <div className="container">
          <div className="alert-header">
            <div className="alert-title">{getAlertTitle()}</div>
            <p style={{ margin: 0, color: '#64748b' }}>
              {clientName} was mentioned on {platform}
            </p>
          </div>

          <div style={{ marginBottom: '30px' }}>
            <h2 style={{ color: '#1f2937', marginBottom: '20px' }}>Citation Details</h2>

            <div className="detail-item">
              <span className="detail-label">Platform:</span>
              <span className="detail-value">{platform}</span>
            </div>

            <div className="detail-item">
              <span className="detail-label">Query:</span>
              <span className="detail-value">"{query}"</span>
            </div>

            <div className="detail-item">
              <span className="detail-label">Position:</span>
              <span className="detail-value">#{position}</span>
            </div>

            <div className="detail-item">
              <span className="detail-label">Sentiment Score:</span>
              <span className="detail-value">{sentimentScore.toFixed(2)}</span>
            </div>
          </div>

          <div className="context-box">
            <h3 style={{ margin: '0 0 12px 0', color: '#374151' }}>Context:</h3>
            <p style={{ margin: 0, fontStyle: 'italic', color: '#64748b' }}>
              "{context}"
            </p>
          </div>

          <div style={{ textAlign: 'center' }}>
            <a href={dashboardUrl} className="cta-button">
              View in Dashboard
            </a>
          </div>

          <div style={{
            marginTop: '40px',
            paddingTop: '20px',
            borderTop: '1px solid #e2e8f0',
            color: '#64748b',
            fontSize: '14px',
            textAlign: 'center'
          }}>
            <p>
              This alert was automatically generated by kreativpique.<br />
              © 2025 {agencyName}. All rights reserved.
            </p>
          </div>
        </div>
      </body>
    </html>
  )
}